<?php
include 'connect.php';
include 'session.php';
require_once('tcpdf_include.php');
error_reporting(0);
ob_start();

$cur_dte=date("Y-m-d");

if(isset($_POST['submit'])){
	$gettask=$_POST['tasks'];
	
class MYPDF extends TCPDF {

	public function Header() {
		include 'connect.php';
		include 'session.php';
		$cur_dte=date("Y-m-d");
		$gettask=$_POST['tasks'];

	$sql="SELECT *,
				 project.startDate AS prostartdte,
				 project.targetDate AS protragetdte,
				 task.startDate AS taskstartdte,
				 task.targetDate AS tasktragetdte
				 FROM project INNER JOIN task ON project.projectID=task.projectID
											WHERE task.taskID='$gettask'
											task.task_status=0";
	$result=mysqli_query($link,$sql);
	$queryinfo1=mysqli_fetch_assoc($result);
	
	 $proj_id=$queryinfo1['projectID'];
	 $proj_nme=$queryinfo1['projectName'];
	 $proj_des=$queryinfo1['projectDesc'];
	 $proj_start=$queryinfo1['prostartdte'];
	 $proj_traget=$queryinfo1['protragetdte'];
	 $proj_client=$queryinfo1['client'];
	 $proj_resperson=$queryinfo1['responsiblePerson'];
	 
	 
	 $task_nme=$queryinfo1['taskName'];
	 $task_description=$queryinfo1['taskDescription'];
	 $task_start=$queryinfo1['taskstartdte'];
	 $task_traget=$queryinfo1['tasktragetdte'];
	 $task_status=$queryinfo1['task_status'];


					  // Get the current page break margin
					$bMargin = $this->getBreakMargin();

					// Get current auto-page-break mode
					$auto_page_break = $this->AutoPageBreak;

					// Disable auto-page-break
					$this->SetAutoPageBreak(false, 0);

					// Define the path to the image that you want to use as watermark.
				
					$this->SetAutoPageBreak($auto_page_break, $bMargin);
					
					// Set the starting point for the page content
					$this->setPageMark();
					
					$img_file1 = 'images/logo.png';
					$this->Image($img_file1, 5, 0, 40, 28, '', '', '', false, 300, '', false, false, 0);
						//$this->SetFont('helvetica', 'B', 20);
						
						
						$html ='<table border="0"  width="100%">
									<tr>
										<td width="100%" >
											<div style="font-size:15px;font-weight:bold;" align="center">WorkTracker</div>
											<div style="font-size:18px;font-weight:bold;" align="center">Sub Task - Task wise</div>
											<div style="font-size:13px;" align="center">'.$cur_dte.'</div>
											
										</td>
									</tr>
							</table>
							';
						$this->writeHTML($html, true, false, true, false, '');
						// Title
		
	  
	}
	public function Footer() {
		include 'session.php';

			//$cur_dte_rtpgen=date("Y-m-d");
			date_default_timezone_set('Asia/Kolkata');
			$cur_dte_rtpgen = date('Y-m-d h:i:s');
			
			$ftext='<table border="0"  width="100%">
						<tr>
							<td width="40%" style="font-size:8px;">'.$ses_user.' &nbsp;&nbsp;&nbsp; '.$cur_dte_rtpgen.'</td>
							<td width="40%" style="font-size:8px;">Report Generated by WorkTracker</td>
							<td width="20%" align="right" style="font-size:8px;">Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages().'</td>
						</tr>
						
					</table>';
        // Position at 15 mm from bottom
        $this->SetY(-6);
        // Set font
        //$this->SetFont('helvetica', 'I', 12);
        // Page number
		$this->writeHTML($ftext, true, false, true, false, '');
    }
}
// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);

$pdf->SetTitle('Sub Tasks - Task wise');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data


// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 32, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
	require_once(dirname(__FILE__).'/lang/eng.php');
	$pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
//$pdf->SetFont('dejavusans', '', 15);

// add a page
$pdf->AddPage();
$pdf->SetFont('times', '', 12);
//$pdf->Image('images/image_demo.jpg', 90, 100, 60, 60, '', '', '', true, 72);
 

	$sql="SELECT *,
				 project.startDate AS prostartdte,
				 project.targetDate AS protragetdte,
				 task.startDate AS taskstartdte,
				 task.targetDate AS tasktragetdte
				 FROM project INNER JOIN task ON project.projectID=task.projectID
											WHERE task.taskID='$gettask'";
	$result=mysqli_query($link,$sql);
	$queryinfo1=mysqli_fetch_assoc($result);
	
	 $proj_id=$queryinfo1['projectID'];
	 $proj_nme=$queryinfo1['projectName'];
	 $proj_des=$queryinfo1['projectDesc'];
	 $proj_start=$queryinfo1['prostartdte'];
	 $proj_traget=$queryinfo1['protragetdte'];
	 $proj_client=$queryinfo1['client'];
	 $proj_resperson=$queryinfo1['responsiblePerson'];
	 
	 
	 $task_nme=$queryinfo1['taskName'];
	 $task_description=$queryinfo1['taskDescription'];
	 $task_start=$queryinfo1['taskstartdte'];
	 $task_traget=$queryinfo1['tasktragetdte'];
	 $task_status=$queryinfo1['task_status'];
	 
	 
	 $query2 ="SELECT *
			FROM staff WHERE empno='$proj_resperson'";
	$result2=mysqli_query($link,$query2);
	$queryinfo2=mysqli_fetch_assoc($result2);
		$proj_respersonnme=$queryinfo2['firstname']." ".$queryinfo2['lastname'];

	  $html='<table class="table" border="1">
						  <tbody>
							<tr>
							  <th>Project Name </th>
							  <td>: '.$proj_nme.'</td>
							  <th>Project Description</th>
							  <td>: '.$proj_des.'</td>
							</tr>
							
							<tr>
							  <th>Start Date </th>
							  <td>: '.$proj_start.'</td>
							  <th>Target Date</th>
							  <td>: '.$proj_traget.'</td>
							</tr>
							
							<tr>
							  <th>Client</th>
							  <td>: '.$proj_client.'</td>
							  <th>Responsible Person</th>
							  <td>: '.$proj_respersonnme.'</td>
							</tr>
							
						  </tbody>
			</table>
			<br>
			<br>';
			
			
		 $html.='<table class="table" border="1">
						  <tbody>
							<tr>
							  <th>Task Name </th>
							  <td>: '.$task_nme.'</td>
							  <th>Task Description</th>
							  <td>: '.$task_description.'</td>
							</tr>
							
							<tr>
							  <th>Start Date </th>
							  <td>: '.$task_start.'</td>
							  <th>Target Date</th>
							  <td>: '.$task_traget.'</td>
							</tr>
						  </tbody>
			</table>
			<br>
			<br>';
			
		$html.='
			<table border="1" width="100%">
				<thead>
					<tr style="font-weight:bold;background-color:#f9f9fa;font-size:12px;">
						<th width="5%">  #</th>
						<th width="10%"> Sub Task ID</th>
						<th width="20%"> Sub Task Name</th>
						<th width="20%"> Sub Task Description</th>
						<th width="10%"> Start Date</th>
						<th width="10%"> Target Date</th>
						<th width="15%"> Project Status</th>
						<th width="10%"> Complete %</th>
					</tr>
				</thead>
				<tbody>';
				$no=0;
				
				$result=mysqli_query($link,"SELECT * FROM subtask
											WHERE taskID='$gettask'");
				while($test = mysqli_fetch_array($result))
				{
					
					$no++;
					$html.='<tr style="font-size:10px;">';
						$html.='<td width="5%" align="center">'.$no.'</td>
						<td width="10%" align="center"> '.$test['subtaskID'].'</td>
						<td width="20%"> '.$test['subtaskName'].'</td>
						<td width="20%"> '.$test['subtaskDesc'].'</td>
						<td width="10%"> '.$test['subtaskstartDate'].'</td>
						<td width="10%"> '.$test['subtasktargetDate'].'</td>';
						if($test['subtask_status']==0){	
							$html.='<td width="15%"> Pending</td>';
						}
						else if($test['subtask_status']==1){
							$html.='<td width="15%"> Complete</td>';
						}
						else{
							$html.='<td width="15%"> Cancelled</td>';
						}
						$html.='<td width="10%"> '.$test['subtaskomplete_presentage'].'%</td>';
					$html.='</tr>';
				}
					
			$html.='</tbody>
			 </table>';
		
 $pdf->writeHTML($html, true, false, true, false, '');


$pdf->lastPage();

// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output('all_tasks_projectwise_'.$getproj.'_'.$cur_dte.'.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+

}
?>